cryptoalpha/api/routes.py
import secrets
import json
import logging
import math
import pandas as pd
import numpy as np
from flask import render_template, request, jsonify, Blueprint
from flask_login import current_user, login_required
from cryptoalpha import db
from cryptoalpha.models import Trades, listofcrypto
from datetime import datetime
from dateutil.relativedelta import relativedelta
from cryptoalpha.users.utils import generatenav, alphavantage_historical

api = Blueprint('api', __name__)


@api.route("/cryptolist", methods=['GET', 'POST'])
# List of available tickers. Also takes argument {term} so this can be used
# in autocomplete forms
def cryptolist():
    getlist = listofcrypto.query.all()

    if request.method == 'GET':
        check = request.args.get('json')
        q = request.args.get('term')
        if check == "true":
            jsonlist = []
            for item in getlist:
                if (q.upper() in item.symbol) or (q in item.name):
                    tmp = {}
                    tmp["name"] = item.name
                    tmp["symbol"] = item.symbol
                    jsonlist.append(tmp)

            return (jsonify(jsonlist))

    return (render_template('cryptolist.html',
                            title="List of Crypto Currencies",
                            listofcrypto=getlist))


@api.route("/aclst", methods=['GET', 'POST'])
@login_required
# Returns JSON for autocomplete on account names.
# Takes on input ?term - which is the string to be found
def aclst():
    list = []
    if request.method == 'GET':
        tradeaccounts = Trades.query.filter_by(
            user_id=current_user.username).group_by(
            Trades.trade_account)
        q = request.args.get('term')
        for item in tradeaccounts:
            if q.upper() in item.trade_account.upper():
                list.append(item.trade_account)

        list = json.dumps(list)

        return list


@api.route("/histvol", methods=['GET', 'POST'])
@login_required
# Returns a json with data to create the vol chart
# takes inputs from get:
# ticker, meta (true returns only metadata), rolling (in days)
# metadata (max, mean, etc)
def histvol():
    # if there's rolling variable, get it, otherwise default to 30
    if request.method == 'GET':
        try:
            q = int(request.args.get('rolling'))
        except ValueError:
            q = 30
    else:
        q = 30

    ticker = request.args.get('ticker')
    metadata = request.args.get('meta')

    # When ticker is not sent, will calculate for portfolio
    if not ticker:
        transactions = Trades.query.filter_by(
            user_id=current_user.username).order_by(
            Trades.trade_date)
        if transactions.count() == 0:
            return render_template('empty.html')

        data = generatenav(current_user.username)
        data['vol'] = data['NAV'].pct_change().rolling(q).std()*(365**0.5)*100
        # data.set_index('date', inplace=True)
        vollist = data[['vol']].copy()
        vollist.index = vollist.index.strftime('%Y-%m-%d')
        datajson = vollist.to_json()

    if ticker:
        filename = 'cryptoalpha/historical_data/'+ticker+'.json'

        try:
            with open(filename) as data_file:
                local_json = json.loads(data_file.read())
                data_file.close()
                prices = pd.DataFrame(local_json[
                    'Time Series (Digital Currency Daily)']).T
                prices['4b. close (USD)'] = prices[
                    '4b. close (USD)'].astype(np.float)
                prices['vol'] = prices[
                    '4b. close (USD)'].pct_change().rolling(q).std()*(
                        365**0.5)*100
                pricelist = prices[['vol']].copy()
                datajson = pricelist.to_json()

        except (FileNotFoundError, KeyError):
            datajson = "Ticker Not Found"
            logging.error(f"File not Found Error: ID: {id}")

    if metadata is not None:
        metatable = {}
        metatable['mean'] = vollist.vol.mean()
        metatable['max'] = vollist.vol.max()
        metatable['min'] = vollist.vol.min()
        metatable['last'] = vollist.vol[-1]
        metatable['lastvsmean'] = ((
            vollist.vol[-1] / vollist.vol.mean()) - 1) * 100
        metatable = json.dumps(metatable)
        return (metatable)

    return datajson


@api.route("/tradedetails", methods=['GET'])
@login_required
# Function that returns a json with trade details given an id
# also, set tradesonly to true to only receive the
# asset side of transaction (buy or sell)
# id = trade hash
def tradedetails():
    if request.method == 'GET':
        id = request.args.get('id')
        # if tradesonly is true then only look for buy and sells
        tradesonly = request.args.get('trades')
        df = pd.read_sql_table('trades', db.engine)
        # Filter only the trades for current user
        df = df[(df.user_id == current_user.username)]
        df = df[(df.trade_reference_id == id)]
        # Filter only buy and sells, ignore deposit / withdraw
        if tradesonly:
            df = df[(df.trade_operation == "B") | (df.trade_operation == "S")]
        # df['trade_date'] = pd.to_datetime(df['trade_date'])
        df.set_index('trade_reference_id', inplace=True)
        df.drop('user_id', axis=1, inplace=True)
        details = df.to_json()
        return(details)


@api.route("/portstats", methods=['GET', 'POST'])
@login_required
# Function retuns summary statistics for portfolio NAV and values
def portstats():
    meta = {}
    # Looking to generate the following data here and return as JSON
    # for AJAX query on front page:
    # Start date, End Date, Start NAV, End NAV, Returns (1d, 1wk, 1mo, 1yr,
    # YTD), average daily return. Best day, worse day. Std dev of daily ret,
    # Higher NAV, Lower NAV + dates. Higher Port Value (date).
    data = generatenav(current_user.username)

    meta['start_date'] = (data.index.min()).date().strftime("%B %d, %Y")
    meta['end_date'] = data.index.max().date().strftime("%B %d, %Y")
    meta['start_nav'] = data['NAV'][0]
    meta['end_nav'] = data['NAV'][-1]
    meta['max_nav'] = data['NAV'].max()
    meta['max_nav_date'] = data[data['NAV'] ==
                                data['NAV'].max()].index.strftime(
        "%B %d, %Y")[0]
    meta['min_nav'] = data['NAV'].min()
    meta['min_nav_date'] = data[data['NAV'] ==
                                data['NAV'].min()].index.strftime(
        "%B %d, %Y")[0]
    meta['end_portvalue'] = data['PORT_usd_pos'][-1]
    meta['max_portvalue'] = data['PORT_usd_pos'].max()
    meta['max_port_date'] = data[data['PORT_usd_pos'] ==
                                 data['PORT_usd_pos'].max()
                                 ].index.strftime("%B %d, %Y")[0]
    meta['min_portvalue'] = round(data['PORT_usd_pos'].min(), 0)
    meta['min_port_date'] = data[data['PORT_usd_pos'] ==
                                 data['PORT_usd_pos'].min()
                                 ].index.strftime("%B %d, %Y")[0]
    meta['return_SI'] = (meta['end_nav'] / meta['start_nav']) - 1
    meta['return_1d'] = (meta['end_nav'] / data['NAV'][-2]) - 1
    meta['return_1wk'] = (meta['end_nav'] / data['NAV'][-7]) - 1
    meta['return_30d'] = (meta['end_nav'] / data['NAV'][-30]) - 1
    meta['return_90d'] = (meta['end_nav'] / data['NAV'][-90]) - 1
    meta['return_ATH'] = (meta['end_nav'] / meta['max_nav']) - 1
    yr_ago = pd.to_datetime(datetime.today() - relativedelta(years=1))
    yr_ago_NAV = data.NAV[data.index.get_loc(yr_ago, method='nearest')]
    meta['return_1yr'] = meta['end_nav'] / yr_ago_NAV - 1

    # create chart data for a small NAV chart

    meta = json.dumps(meta)
    return meta


@api.route("/navchartdatajson", methods=['GET', 'POST'])
@login_required
#  Creates a table with dates and NAV values
def navchartdatajson():
    data = generatenav(current_user.username)
    # Generate data for NAV chart
    navchart = data[['NAV']].copy()
    # dates need to be in Epoch time for Highcharts
    navchart.index = (navchart.index - datetime(1970, 1, 1)).total_seconds()
    navchart.index = navchart.index * 1000
    navchart.index = navchart.index.astype(np.int64)
    navchart = navchart.to_dict()
    navchart = navchart['NAV']
    navchart = json.dumps(navchart)
    return navchart


@api.route("/manage_custody",  methods=['GET'])
@login_required
# Back-end function to manage positions after requests are sent from
# the edit position tool from account_positions.html
def manage_custody():
    tradedetails = "EMPTY"
    # If method is post then do actions
    if request.method == "GET":
        action = request.args.get('action')
        if action == "delete_dust":
            try:
                ticker = request.args.get('ticker')
                quant_before = request.args.get('quant_before')
                from_account = request.args.get('from_account')
                # Implement the trade and write to dbase
                tradedetails = f'Trade included to wipe out {ticker} ' + \
                    f'dust amount of {quant_before} from ' +\
                    f'{from_account}'

                tradedate = datetime.now()
                # Create a unique ID
                random_hex = secrets.token_hex(21)
                if float(quant_before) < 0:
                    acc = "B"
                else:
                    acc = "S"
                trade = Trades(user_id=current_user.username,
                               trade_date=tradedate,
                               trade_account=from_account,
                               trade_asset_ticker=ticker,
                               trade_operation=acc,
                               trade_price="0",
                               trade_quantity=float(quant_before) * (-1),
                               trade_fees=0,
                               cash_value=0,
                               trade_notes=tradedetails,

cryptoalpha/portfolio/routes.py
import pandas as pd
import numpy as np
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from cryptoalpha import db, mhp as mrh
from cryptoalpha.models import Trades
from datetime import datetime
from cryptoalpha.users.utils import (generatenav, generate_pos_table,
                                     generatepnltable)

portfolio = Blueprint('portfolio', __name__)


@portfolio.route("/portfolio")
@login_required
# Home Page - details of the portfolio
def portfolio_main():
    user = current_user.username
    transactions = Trades.query.filter_by(user_id=current_user.username)
    if transactions.count() == 0:
        return render_template('empty.html')

    portfolio_data, pie_data = generate_pos_table(user, "USD", False)
    if portfolio_data == "ConnectionError":
        return render_template('offline.html', title="Connection Error")
    return render_template('portfolio.html', title="Portfolio View",
                           portfolio_data=portfolio_data, pie_data=pie_data)


@portfolio.route("/navchart")
# Page with a single historical chart of NAV
# Include portfolio value as well as CF_sumcum()
@login_required
def navchart():
    data = generatenav(current_user.username)
    navchart = data[['NAV']].copy()
    # dates need to be in Epoch time for Highcharts
    navchart.index = (navchart.index - datetime(1970, 1, 1)).total_seconds()
    navchart.index = navchart.index * 1000
    navchart.index = navchart.index.astype(np.int64)
    navchart = navchart.to_dict()
    navchart = navchart['NAV']

    port_value_chart = data[['PORT_cash_value',
                             'PORT_usd_pos', 'PORT_ac_CFs']].copy()
    port_value_chart['ac_pnl'] = port_value_chart['PORT_usd_pos'] -\
        port_value_chart['PORT_ac_CFs']
    # dates need to be in Epoch time for Highcharts
    port_value_chart.index = (port_value_chart.index -
                              datetime(1970, 1, 1)).total_seconds()
    port_value_chart.index = port_value_chart.index * 1000
    port_value_chart.index = port_value_chart.index.astype(np.int64)
    port_value_chart = port_value_chart.to_dict()

    return render_template('navchart.html', title="NAV Historical Chart",
                           navchart=navchart,
                           port_value_chart=port_value_chart)


@portfolio.route("/heatmap")
@login_required
# Returns a monthly heatmap of returns and statistics
def heatmap():
    # If no Transactions for this user, return empty.html
    transactions = Trades.query.filter_by(
        user_id=current_user.username).order_by(
        Trades.trade_date)
    if transactions.count() == 0:
        return render_template('empty.html')

    # Generate NAV Table first
    data = generatenav(current_user.username)
    data['navpchange'] = ((data['NAV'] / data['NAV'].shift(1)) - 1)
    returns = data['navpchange'].copy()
    # Run the mrh function to generate heapmap table
    heatmap = mrh.get(returns, eoy=True)

    heatmap_stats = heatmap.copy()
    cols = ['Jan', 'Feb', 'Mar', 'Apr', 'May',
            'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'eoy']
    cols_months = ['Jan', 'Feb', 'Mar', 'Apr', 'May',
                   'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    years = heatmap.index.to_list()
    heatmap_stats['MAX'] = heatmap_stats[
        heatmap_stats[cols_months] != 0].max(axis=1)
    heatmap_stats['MIN'] = heatmap_stats[
        heatmap_stats[cols_months] != 0].min(axis=1)
    heatmap_stats['POSITIVES'] = heatmap_stats[
        heatmap_stats[cols_months] > 0].count(axis=1)
    heatmap_stats['NEGATIVES'] = heatmap_stats[
        heatmap_stats[cols_months] < 0].count(axis=1)
    heatmap_stats['POS_MEAN'] = heatmap_stats[
        heatmap_stats[cols_months] > 0].mean(axis=1)
    heatmap_stats['NEG_MEAN'] = heatmap_stats[
        heatmap_stats[cols_months] < 0].mean(axis=1)
    heatmap_stats['MEAN'] = heatmap_stats[
        heatmap_stats[cols_months] != 0].mean(axis=1)

    return render_template('heatmap.html',
                           title="Monthly Returns HeatMap",
                           heatmap=heatmap,
                           heatmap_stats=heatmap_stats,
                           years=years, cols=cols)


@portfolio.route("/volchart", methods=['GET', 'POST'])
@login_required
# Only returns the html - request for data is done through jQuery AJAX
def volchart():
    return render_template('volchart.html',
                           title="Historical Volatility Chart")


@portfolio.route("/pnl", methods=['GET', 'POST'])
@login_required
# Function to return a table with realized PnL and matching Tables
# takes ticker, method and dates as arguments
def pnl():
    if request.method == 'GET':
        id = request.args.get('id')
        method = request.args.get('method')
        start = request.args.get('start')
        end = request.args.get('end')

    realpnl, metadata = generatepnltable(current_user.username, id,
                                         method, start, end)
    # realpnl = json.dumps(realpnl, indent=4)
    return render_template('pnl.html', realpnl=realpnl, metadata=metadata,
                           title="PnL History")


@portfolio.route("/portfolio_compare",  methods=['GET'])
@login_required
def portfolio_compare():
    return render_template('portfolio_compare.html',
                           title="Portfolio Comparison")

cryptoalpha/templates/about.html
{% extends "layout.html" %}
{% block content %}
<!-- http://jquery.com/ -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<div class="row">
    <div class="col-sm-10 col-md-10">
        <div class="thumbnail">
            <h1>
                CryptoBlotter v.01

            <img src="static/images/bitcoin-logo-gray.jpg" width="40" height="40" alt="Bitcoin">
            </h1>
            <hr>
            <div class="caption">
                <p>
                    Please note that this is an ALPHA version still under development and test.
                    Use at your own risk. We cannot guarantee the accuracy of the data and we will be reseting the database from time to time.
                    Your trades may get deleted.
                </p>

                    This is work in progress. If you have suggestions or feedback please
                    <a href="/contact">click here</a>
                </p>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

cryptoalpha/templates/emptyaccounts.html
{% extends "layout.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<div class="container">
    <div class="row align-middle">
        <div class="col-sm-8 align-middle">
            <h4>
                Your Account List appears to be empty and no accounts were found </br>
            </h4></br>

                <h6>Maybe you are new here?</h6>
                You can start by including a new account</br></br>

                <div class="container">
                <form method="POST" action="" enctype="multipart/form-data">
                    <!-- Important to include the below for added security -->
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">


                        <div class="form-group">

                            {{ form.account_name.label(class="form-control-label") }}
                            {{ form.account_name(class="form-control form-control-sm")}}

                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info")}}
                    </div>
                </form>
                </div>


        </br>
        </br>
                You should include: </br>
                <ul>
                    <li>Trade and Custody accounts: like crypto exchanges</li>
                    <li>Hardware Wallets</li>
                    <li>Bank Accounts: to properly manage cashflow</li>
                    <li>Any other account where you hold or transact crypto</li>
                </ul>




        </div>

        <div class="col-sm-4 align-middle text-center">
        </br></br></br></br>
            <img class="mx-auto d-block" src="static/images/empty.png" width="75" height="125"></img>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{% endblock content %}

cryptoalpha/templates/layout.html
<!DOCTYPE html>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<html>
    <link rel="icon" href="static/images/favicon-bitcoin.ico" class="invert">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>CryptoBlotter | {{ title }}</title>
    {% else %}
        <title>CryptoBlotter</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container max-width">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


        <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <a class="navbar-brand" href="/">
                        <i class="fas fa-home"></i>
                    </a>
                </li>

                {% if current_user.is_authenticated %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account Tools</a>
                    <div class="dropdown-menu">
                         <a class="dropdown-item" href="{{ url_for('main.importcsv') }}"><i class="fas fa-file-import"></i>&nbsp;&nbsp;Import CSV file</a>
                         <a class="dropdown-item" href="{{ url_for('main.csvtemplate') }}"><i class="fas fa-book"></i>&nbsp;&nbsp;CSV file instructions</a>
                         <a class="dropdown-item" id="downloadcsv" href="{{ url_for('main.exportcsv') }}"><i class="fas fa-download"></i>&nbsp;&nbsp;Download all your transactions in CSV</a>
                         <div class="dropdown-divider"></div>
                         <a class="dropdown-item" href="{{ url_for('users.account') }}"><i class="fas fa-users-cog"></i>&nbsp;&nbsp;Manage User Account</a>
                         <div class="dropdown-divider"></div>
                         <a class="dropdown-item" href="{{ url_for('main.about') }}"><i class="fab fa-bitcoin"></i>&nbsp;&nbsp;About CryptoBlotter</a>
                   </div>
                 </li>
                 <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>

                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Portfolio Actions</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('transactions.list_transactions') }}"><i class="fas fa-list"></i>&nbsp;&nbsp;List Transactions</a>
                        <a class="dropdown-item" href="{{ url_for('transactions.newtrade') }}"><i class="fas fa-plus-square"></i>&nbsp;&nbsp;Include New Transaction</a>
                        <a class="dropdown-item" href="{{ url_for('transactions.account_positions') }}"><i class="fas fa-key"></i>&nbsp;&nbsp;Custody List</a>
                    </div>
                </li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>


                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Portfolio Analysis</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i>&nbsp;&nbsp;Overview</a>
                        <a class="dropdown-item" href="{{ url_for('portfolio.navchart') }}"><i class="fas fa-chart-area"></i>&nbsp;&nbsp;Portfolio Historical Chart</a>
                        <a class="dropdown-item" href="{{ url_for('portfolio.portfolio_compare') }}"><i class="fas fa-check-double"></i>&nbsp;&nbsp;Compare Portfolio Performance</a>
                        <a class="dropdown-item" href="{{ url_for('portfolio.volchart') }}"><i class="fas fa-cloud-sun-rain"></i>&nbsp;&nbsp;Historical Volatility Chart</a>
                        <a class="dropdown-item" href="{{ url_for('portfolio.heatmap') }}"><i class="fas fa-fire-extinguisher"></i>&nbsp;&nbsp;Monthly HeatMap</a>
                    </div>
                </li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>

                <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Other Tools</a>
                   <div class="dropdown-menu">
                       <a class="dropdown-item" href="https://hodlcalculator.herokuapp.com/" target="_blank"><i class="fas fa-calculator"></i>&nbsp;&nbsp;HODL Calulator&nbsp;<i class="fas  fa-xs fa-external-link-alt"></i></a>
                   </div>
               </li>

            {% endif %}

            </div>
        </div>

            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">
                    <i class="fas fa-users-cog"></i>
                </a>

                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>

        </div>

      </nav>
    </header>


    <main role="main" class="container max-width">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- http://jquery.com/ & jQuery UI -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>

    <script
      src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
      integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
      crossorigin="anonymous">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/flick/jquery-ui.css"
    <br><br><br>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <br><br>
                <div id="messagealert" class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
    <br>
          {% block content %}{% endblock %}
    <br>
    <!-- Footer -->
    <footer class="site-footer bg-steel small fixed-bottom">
        <div class="container text-right text-light align-middle">
        </br>
        <i class="fab fa-bitcoin fa-2x"></i> #StackingSats #NotYourKeysNotYourCoins&nbsp;&nbsp;&nbsp;
        <i class="fab fa-github-square fa-2x"></i>&nbsp;Open Source code available at <a href='https://github.com/pxsocs/cryptoblotter' class='text-white'>GitHub</a>
    </br></br>
        </div>
    </footer>
  </main>
</body>
</html>

cryptoalpha/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}